HHF/config/routes.rb
HHF::Application.routes.draw do

  #Routes for Session resource:
  get '/login', controller: 'sessions', action: 'new'
  post '/sessions', controller: 'sessions', action: 'create'
  get "/logout", controller: 'sessions', action: 'remove'

  post "/search", controller: 'movies', action: 'filter'

  # Routes for the User resource:
  # CREATE
  get '/users/new', controller: 'users', action: 'new', as: 'new_user'
  post '/users', controller: 'users', action: 'create'

  # READ
  get '/users', controller: 'users', action: 'index', as: 'users'
  get '/users/:id', controller: 'users', action: 'show', as: 'user'

  # UPDATE
  get '/users/:id/edit', controller: 'users', action: 'edit', as: 'edit_user'
  put '/users/:id', controller: 'users', action: 'update'

  # DELETE
  delete '/users/:id', controller: 'users', action: 'destroy'
  #------------------------------

  # Route for our home page.
  get '/home', controller: 'products', action: 'index'

  get "/products", controller: 'products', action: 'index'
  post "/products", controller: 'products', action: 'create'

  get '/products/new', controller: 'products', action: 'new', as: 'new_product'

  get '/products/:id', controller: 'products', action: 'show'
  put '/products/:id', controller: 'products', action: 'update'

  delete '/products/:id', controller: 'products', action: 'remove'

  get "/products/:id/edit", controller: 'products', action: 'edit'

end

HHF/app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :description, :detail, :price, :title

    validates :title, presence: true, uniqueness: true

end

HHF/app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password

end

HHF/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

HHF/app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def remove
    m = Product.find_by_id(params["id"])
    m.remove
    redirect_to "/products"
  end

  def index
      sort_direction = params["sortby"]
      if sort_direction == nil
        sort_direction = "asc"
      end
      @products = Product.order("title #{sort_direction}").limit(100)
  end

  def show
      @product = Product.find_by_id(params["id"])
      session["last_product_id"] = @product.id
  end

  def create
      @product = Product.new
      @product.title = params[:title]
      @product.description = params[:description]
      @product.detail = params[:detail]
      @product.price = params[:price]
      if @product.save
        redirect_to "/products"
      else
        redirect_to "/products/new", notice: "Nice try."
      end
    end

    def new
    if session["user_id"].blank?
      redirect_to "/products", notice: "Please sign in first."
    end
  end
end

HHF/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def remove
    session["user_id"] = nil
    redirect_to "/products", notice: "Come back soon!"
  end

  def new
  end

  def create
    user = User.find_by_name(params["name"])

    if user && user.authenticate(params["password"])
      session["user_id"] = user.id
      redirect_to "/products", notice: "Welcome back, #{user.name}"
    else
      redirect_to "/login", notice: "Unknown username or password."
    end

  end
end

HHF/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find_by_id(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new
    @user.name = params[:name]
    @user.password = params[:password]

    if @user.save
      session["user_id"] = @user.id
      redirect_to products_url
    else
      render 'new'
    end
  end

  def edit
    @user = User.find_by_id(params[:id])
  end

  def update
    @user = User.find_by_id(params[:id])
    @user.name = params[:name]
    @user.password = params[:password]

    if @user.save
      redirect_to users_url
    else
      render 'new'
    end
  end

  def destroy
    @user = User.find_by_id(params[:id])
    @user.destroy
    redirect_to users_url
  end
end

HHF/app/helpers/application_helper.rb
module ApplicationHelper
end

HHF/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HUGS 'N HIGH FIVES</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <header>
    <h1>HUGS 'N HIGH FIVES</h1>
    <nav>
      <%= link_to "Hugs n' High Fives", '/products' %> |

      <% if session["user_id"].present? %>
        Hello, <%= User.find_by_id(session["user_id"]).name %>!
        <%= link_to "Sign Out", "/logout" %>
      <% else %>
        <%= link_to "Sign Up", '/users/new' %>
        <%= link_to "Login", '/login' %>
      <% end %>

    </nav>
      <%= form_tag '/search' do %>
        <%= text_field_tag :term, "", placeholder: 'Search...' %>
      <% end %>

  </header>

  <div class="notice"><%= notice %></div>

  <%= yield %>

</body>
</html>

HHF/app/views/products/index.html.erb
<% if session["user_id"] %>
  <p>
    <%= link_to "Add a New Product", '/products/new' %>
  </p>
<% end %>

<table>
  <thead>
    <tr>
      <th></th>
      <th><%= link_to "Title", "/products?sortby=desc" %></th>
      <th>Description</th>
    </tr>
  </thead>
  <tbody>
  <% @products.each do |product| %>
    <tr>
      <td>
        <%= link_to "Remove", "products/#{product.id}", method: 'delete' %>
        <%= link_to "Edit", "products/#{product.id}/edit" %>
      </td>
      <td><%= link_to product.title, "/products/#{product.id}" %></td>
      <td><%= product.description %></td>
    </tr>
  <% end %>
  </tbody>
</table>

HHF/app/views/products/new.html.erb
<h1>Add a Hug or High Five</h1>

<%= form_tag "/products" do %>
  <p>
    <%= label_tag :title, "Type of Hug" %>
    <%= text_field_tag :title, "", size: 80, placeholder: "Enter hug type here..." %>
  </p>
  <p>
    <%= label_tag :description, "Description" %>
    <%= text_field_tag :description, "Enter description here... ", size: 100 %>
  </p>
   <p>
    <%= label_tag :detail, "Hug detail" %>
    <%= text_area_tag :detail, "Enter detail here... ", size: "100x10" %>
  </p>
   <p>
    <%= label_tag :price, "Price" %>
    <%= text_field_tag :price, "Enter price here... ", size: 8 %>
  </p>
  <%= submit_tag "Submit" %>

<% end %>

HHF/app/views/products/show.html.erb
<h1><%= @product.title %></h1>

<p>Description: <%= @product.description %></p>
<p>Product Detail: <%= @product.detail %></p>
<p>Price: <%= @product.price %></p>

HHF/app/views/users/edit.html.erb
<h1>Editing User #<%= @user.id %></h1>


<%= form_tag(user_url(@user), method: 'put') do %>

  <div>
    <%= label_tag :name %><br />
    <%= text_field_tag :name, @user.name %>
  </div>

  <div>
    <%= label_tag :password %><br />
    <%= text_field_tag :password, @user.password %>
  </div>


  <div>
    <%= submit_tag "Update User" %>
  </div>

<% end %>

HHF/app/views/users/index.html.erb
<h1>Users</h1>

<p><%= link_to 'Add a New User', new_user_url %></p>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Password</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.name %></td>
      <td><%= user.password %></td>

      <td><%= link_to 'Show', user_url(user) %></td>
      <td><%= link_to 'Edit', edit_user_url(user) %></td>
      <td><%= link_to 'Remove', user_url(user), method: 'delete', data: { confirm: "Do you really want to delete this user?" } %></td>

    </tr>
  <% end %>
  </tbody>
</table>

HHF/app/views/users/new.html.erb
<h1>New User</h1>


<%= form_tag(users_url, method: 'post') do %>


  <div>
    <%= label_tag :name %><br />
    <%= text_field_tag :name %>
  </div>

  <div>
    <%= label_tag :password %><br />
    <%= password_field_tag :password %>
  </div>


  <div>
    <%= submit_tag "Create User" %>
  </div>
<% end %>

HHF/app/views/users/show.html.erb
<h1>User #<%= @user.id %></h1>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Password:</b>
  <%= @user.password %>
</p>